server:
  port: 8081
cors:
  allowed-origins: "*"
adapters:
  restconsumer:
    auth:
      baseUrl: "http://autenticacion:8082/api/v1/usuarios/"
  r2dbc:
    host: "sol-db"
    port: 5432
    database: "soldb"
    schema: "public"
    username: "soluser"
    password: "solpass"
  sqs:
    region: "us-east-1"
    queueUrl: "https://sqs.us-east-1.amazonaws.com/825765403293/PragmaNotificationQueue"
    endpoint: "https://sqs.us-east-1.amazonaws.com/825765403293/PragmaNotificationQueue" # For localstack only

security:
  jwt:
    secret: "kYf5mJvQx6jR1LWYiwvhP2Z5gTw4Xt4lUOpd4XyD5rk=" # debe coincidir con auth-service
    expiration: 3600 # 1h en s