server:
  port: 8081
cors:
  allowed-origins: "*"
adapters:
  restconsumer:
    auth:
      baseUrl: "http://localhost:8082/api/v1/usuarios/"
  r2dbc:
    host: "localhost"
    port: 5432
    database: "pragma_reactive"
    schema: "public"
    username: "app_user"
    password: "app_pass"
  sqs:
    region: "us-east-1"
    queueUrl: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/pragma-notification-queue"
    endpoint: "http://localhost:4566"
entrypoint:
  sqs:
    region: "us-east-1"
    endpoint: "http://localhost:4566"
    queueUrl: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/pragma-capacitydebt-queue"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
security:
  jwt:
    secret: "kYf5mJvQx6jR1LWYiwvhP2Z5gTw4Xt4lUOpd4XyD5rk=" # debe coincidir con auth-service
    expiration: 3600 # 1h en s