server:
  port: 8082
spring:
  application:
    name: "MsSolicitudes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "pragma_reactive"
    schema: "public"
    username: "app_user"
    password: "app_pass"

logging:
  level:
    root: INFO
    org.springframework: INFO
    co.com.bancolombia: DEBUG
    reactor.netty: WARN